dotenv : .env
dependencies: 
    - OpenZeppelin/openzeppelin-contracts@4.4.0
wallets : 
  beacon: ${BEACON}
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"